(ns raster.compiler.cljs-emit
  "P1/P2 — the build-time half of the cljs↔wasm binding.

   Compiles a set of raster `deftm` kernels to ONE shared-memory wasm module and
   generates a ClojureScript counterpart of the kernel namespace, so a `.cljc`
   game can `(require [asteroids.kernels])` and get the right impl per platform:
   the JVM `deftm`/`defvalue` source (bytecode), or this generated `.cljs`
   (a `defrecord` per `defvalue` + a wasm-backed wrapper per `deftm`).

   `deftm`/`defvalue` stay `:clj`-only macros; the cljs side is *generated*, AOT.
   Value types cross the boundary per the wasm calling convention: a value-type
   param is passed field-by-field; a value-type return comes back as a wasm
   multi-value JS array and is reconstructed into the record.

   The generated namespace's records + wrappers are built as Clojure FORMS and
   `pr-str`'d (not string-concatenated) — the static preamble is the only string.

   Kernel spec: {:var #'ns/move-shape :export \"move_shape\" :fn \"move-shape\"
                 :dtype :double :wasm-simd? true}."
  (:require [raster.compiler.pipeline :as pl]
            [raster.compiler.core.types :as types]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- value-type? [tag] (contains? @types/soa-registry tag))
(defn- field-names [tag] (mapv :name (:fields (get @types/soa-registry tag))))

(defn- kernel-sig
  "Semantic signature (from the threaded :sig) → param/return value-type info."
  [{:keys [param-names param-tags return-tag]}]
  {:params (mapv (fn [nm t]
                   (if (value-type? t)
                     {:kind :value :name (name nm) :tag t :fields (field-names t)}
                     {:kind :scalar :name (name nm)}))
                 param-names param-tags)
   :ret (cond (value-type? return-tag) {:kind :value :tag return-tag :fields (field-names return-tag)}
              (nil? return-tag)        {:kind :void}
              :else                    {:kind :scalar})})

(defn- record-form [tag]
  (list 'defrecord (symbol (name tag)) (mapv symbol (field-names tag))))

(defn- wrapper-form
  "cljs fn form for one kernel: marshal value-type record args to field values,
   call the wasm export, reconstruct a record from a value-type multi-value return."
  [export fname {:keys [params ret]}]
  (let [arglist   (mapv (comp symbol :name) params)
        call-args (vec (mapcat (fn [{:keys [kind name fields]}]
                                 (if (= :value kind)
                                   (map #(list (symbol (str ".-" %)) (symbol name)) fields)  ; (.-x s)
                                   [(symbol name)]))
                               params))
        call (list* (list 'kfn export) call-args)]
    (if (= :value (:kind ret))
      (list 'defn (symbol fname) arglist
            (list 'let ['r call]
                  (list* (symbol (str "->" (name (:tag ret))))
                         (map-indexed (fn [i _] (list 'aget 'r i)) (:fields ret)))))
      (list 'defn (symbol fname) arglist call))))

(defn- preamble [ns]
  (str ";; GENERATED by raster.compiler.cljs-emit — do not edit.\n"
       ";; cljs counterpart of the raster kernel ns " ns " (deftm/defvalue → wasm).\n"
       "(ns " ns "\n  (:require [raster.wasm :as w]))\n\n"
       "(defonce M (atom nil))\n"
       "(defn init!\n"
       "  ([src] (init! src (cljs.core/js-obj)))\n"
       "  ([src env] (.then (w/instantiate! src env) (fn [s] (reset! M s) s))))\n"
       "(defn ready? [] (some? @M))\n"
       "(defn- kfn [n] (w/export @M n))\n"))

(defn emit!
  "Compile `kernels` to one wasm module + a generated cljs ns (same name as the
   kernel source ns) with records + wasm-backed wrappers.
   opts: {:kernels [spec…] :ns 'asteroids.kernels :out-dir … :wasm-name \"kernels\"}.
   Returns {:wasm-file :cljs-file :exports}."
  [{:keys [kernels ns out-dir wasm-name] :or {wasm-name "kernels"}}]
  (let [module      (pl/compile-wasm-module
                     (mapv (fn [{:keys [var export dtype wasm-simd?]}]
                             {:var var :name export :dtype (or dtype :double) :wasm-simd? wasm-simd?})
                           kernels))
        sig-by-name (into {} (map (juxt :name :sig) (:exports module)))
        ksigs       (mapv (fn [{:keys [export] fname :fn}]
                            {:export export :fname fname :sig (kernel-sig (sig-by-name export))})
                          kernels)
        value-tags  (->> ksigs
                         (mapcat (fn [{:keys [sig]}]
                                   (concat (keep #(when (= :value (:kind %)) (:tag %)) (:params sig))
                                           (when (= :value (:kind (:ret sig))) [(:tag (:ret sig))]))))
                         distinct vec)
        forms       (concat (map record-form value-tags)
                            (map (fn [{:keys [export fname sig]}] (wrapper-form export fname sig)) ksigs))
        src         (str (preamble ns) "\n" (str/join "\n" (map pr-str forms)) "\n")
        wasm-file   (io/file out-dir (str wasm-name ".wasm"))
        cljs-file   (io/file out-dir (str (str/replace (str ns) #"[.-]" {"." "/" "-" "_"}) ".cljs"))]
    (io/make-parents wasm-file)
    (with-open [o (io/output-stream wasm-file)] (.write o ^bytes (:bytes module)))
    (io/make-parents cljs-file)
    (spit cljs-file src)
    {:wasm-file (.getPath wasm-file) :cljs-file (.getPath cljs-file) :exports (:exports module)}))
