(ns raster.compiler.cljs-emit
  "P1 — the build-time half of the cljs↔wasm binding.

   Takes a set of raster `deftm` kernels, compiles them to ONE shared-memory wasm
   module (via pipeline/compile-wasm-module), and emits two artifacts a
   ClojureScript app consumes:

     <out-dir>/<wasm-name>.wasm   — the compiled kernels (one shared linear memory)
     <out-dir>/<gen-path>.cljs    — a generated wrapper namespace

   The generated namespace requires the hand-written `raster.wasm` loader, holds
   the instantiated module, exposes `init!` (async) + typed-array memory views,
   and a thin positional wrapper fn per kernel that calls the wasm export. So a
   cljs author writes no interop: `(require [game.kernels :as k])`, `(k/init!
   bytes)` once, then `(k/move-shapes! …)` as an ordinary fn — the deftm is
   `:clj`-only and never seen by the cljs compiler. This is the AOT story: the
   front-half runs here at build time; the browser only loads wasm.

   Kernel spec: {:var #'ns/move-shapes! :export \"move_shapes\" :fn \"move-shapes!\"
                 :dtype :double :wasm-simd? true}."
  (:require [raster.compiler.pipeline :as pl]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- wrapper-defn
  "Generated positional wrapper for one export. Arity = #wasm params; args pass
   straight through (array params are (ptr) byte-offsets, scalars are values —
   the caller owns the SoA layout in linear memory)."
  [{:keys [export fn param-types result-types]}]
  (let [args (mapv #(symbol (str "a" %)) (range (count param-types)))]
    (str "(defn " fn " [" (str/join " " args) "]\n"
         "  ((kfn \"" export "\")" (when (seq args) " ") (str/join " " args) "))"
         "  ;; " (count param-types) " params, result " (if (seq result-types) result-types "void"))))

(defn emit!
  "Compile `kernels` to one wasm module + a generated cljs wrapper ns.
   opts: {:kernels [spec…] :ns 'game.kernels :out-dir \"path\" :wasm-name \"kernels\"}.
   Returns {:wasm-file :cljs-file :exports}."
  [{:keys [kernels ns out-dir wasm-name] :or {wasm-name "kernels"}}]
  (let [module (pl/compile-wasm-module
                (mapv (fn [{:keys [var export dtype wasm-simd?]}]
                        {:var var :name export :dtype (or dtype :double) :wasm-simd? wasm-simd?})
                      kernels))
        ;; pair each export with its requested cljs fn name
        by-export (into {} (map (juxt :export identity) kernels))
        exports   (mapv (fn [e] (assoc e :fn (:fn (by-export (:name e))) :export (:name e))) (:exports module))
        wasm-file (io/file out-dir (str wasm-name ".wasm"))
        cljs-file (io/file out-dir (str (str/replace (str ns) #"[.-]" {"." "/" "-" "_"}) ".cljs"))
        ns-src (str ";; GENERATED by raster.compiler.cljs-emit — do not edit.\n"
                    ";; raster deftm kernels compiled to wasm (" wasm-name ".wasm); call as ordinary cljs fns.\n"
                    "(ns " ns "\n  (:require [raster.wasm :as w]))\n\n"
                    "(defonce ^:private M (atom nil))\n\n"
                    "(defn init!\n"
                    "  \"Instantiate the kernels module (async). `src` = a URL string or the\n"
                    "   wasm bytes; `env` = optional import object (transcendental host fns).\"\n"
                    "  ([src] (init! src #js {}))\n"
                    "  ([src env] (.then (w/instantiate! src env) (fn [s] (reset! M s) s))))\n\n"
                    "(defn ready? [] (some? @M))\n"
                    "(defn memory [] (w/memory @M))\n"
                    "(defn f64 [] (w/f64-view @M))\n"
                    "(defn f32 [] (w/f32-view @M))\n"
                    "(defn i32 [] (w/i32-view @M))\n"
                    "(defn- kfn [n] (w/export @M n))\n\n"
                    (str/join "\n" (map wrapper-defn exports))
                    "\n")]
    (io/make-parents wasm-file)
    (with-open [o (io/output-stream wasm-file)] (.write o ^bytes (:bytes module)))
    (io/make-parents cljs-file)
    (spit cljs-file ns-src)
    {:wasm-file (.getPath wasm-file)
     :cljs-file (.getPath cljs-file)
     :exports   exports}))
