(ns raster.compiler.passes.parallel.scalar-expression-body
  "Lower a typed scalar S-expression region to target-neutral KernelBody SSA.

   This is shared by ordinary maps and ordered fold-maps. The caller supplies authoritative
   storage/scalar dtypes, index lowering, participation, and its own structured decline function;
   this pass performs no source-level type or function inference."
  (:require [raster.compiler.backend.intrinsics :as intrinsics]
            [raster.compiler.core.dtype :as dtype]
            [raster.compiler.core.inference :as inference]
            [raster.compiler.core.numeric-constant :as numeric-constant]
            [raster.compiler.core.scalar-conversion :as scalar-conversion]
            [raster.compiler.core.op-descriptor :as descriptor]
            [raster.compiler.core.types :as types]
            [raster.compiler.core.util :as util]
            [raster.compiler.ir.kernel-body :as body]
            [raster.compiler.ir.scalar-range :as scalar-range]
            [raster.compiler.ir.soac-dialect :as dialect]
            [raster.compiler.passes.parallel.patterns :as patterns]))

(defn- contains-indexed-load?
  [expression]
  (boolean (some descriptor/aget-call? (tree-seq coll? seq expression))))

(defn- match-ordered-loop
  "Recognize the canonical one-index/one-carry loop without authorizing reassociation."
  [expression]
  (when-let [matched (patterns/match-ordered-reduce-loop expression)]
    (assoc matched
           :inclusive? (= :inclusive (:bound-mode matched))
           :update-expr (:scoped-update-expr matched))))

(defn make-lowerer
  "Build a scalar-expression lowerer.

   Returns source lowering entries `:lower` and `:lower-region`, plus typed builder entries
   `:cast`, `:load` and `:compute`. `:lower` accepts expression, expected dtype, and a map of typed
   local values. `:lower-region` accepts an ordered {:bindings [...] :results [...]} region, result dtypes,
   retained binding dtypes, and typed locals; it returns shared SSA operations and ordered results.
   Neither entry point stores tuple results: the schedule must commit all components together.
   `decline!` is called as `(decline! rule message data)` so each owning schedule retains an honest,
   local coverage contract. `:cast` converts an already-lowered value to a target dtype, with source
   context as its third argument. Owners may supply `conversion-policy` (source/target dtypes)
   and `load-other` (storage dtype); these do not change source-language admission.
   `require-source-types?` requires retained compound source dtypes at conversion boundaries
   and preserves retained integral arithmetic before floating consumer conversion. Older
   packed owners retain their explicit widened-integer policy until separately migrated.
   `scalar-ranges` may carry owner-proved intervals for declared integral scalar inputs. This
   builder validates their shape and representability but the owner remains responsible for the
   semantic proof establishing a tighter interval than the declared dtype.
   Fragment callers may supply their complete `source-region` up front. Together with the declared
   scalar/array/index scope this reserves source identities once; subsequent environments must
   contain only those identities or values generated by this builder.
   `:load` accepts a declared buffer and proved coordinate vector; `:compute` accepts a canonical
   operator, result dtype, already-converted argument vector and explicit operation options.
   `:fresh-binding` reserves an SSA identity for an owner's structured-control binder.
   These typed entries leave admission and proofs to the owner and final KernelBody validation."
  [{:keys [array-types scalar-types scalar-ranges arrays index-scope lower-index predicate id-prefix decline!
           conversion-policy load-other source-region require-source-types?]
    :or {id-prefix "scalar" scalar-ranges {}}}]
  (let [canon-type #(if (= :predicate %) :predicate (dtype/canon %))
        normalized-form (fn [form type source]
                          (with-meta form (assoc (meta source) :raster.type/tag
                                                 (dtype/scalar-tag-for-dtype type))))
        counter (atom 0)
        reserved (atom (set (concat arrays (keys array-types) (keys scalar-types) index-scope)))
        reserve! (fn [form]
                   (swap! reserved into (filter symbol? (tree-seq coll? seq form))))
        _ (reserve! [source-region predicate])
        fresh (fn [prefix]
                (loop []
                  (let [id (symbol (str id-prefix "-" prefix "-" (swap! counter inc)))]
                    (if (contains? @reserved id)
                      (recur)
                      (do (swap! reserved conj id) id)))))
        validated-scalar-ranges
        (into {}
              (map (fn [[id range]]
                     (let [type (some-> (get scalar-types id) canon-type)]
                       (when-not (and (symbol? id) type
                                      (map? range) (integer? (:lower range))
                                      (integer? (:upper range))
                                      (<= (:lower range) (:upper range))
                                      (scalar-range/contained-in-dtype? range type))
                         (throw (ex-info "owner scalar range must fit its declared integral dtype"
                                         {:reason :invalid-scalar-range-proof
                                          :scalar id :range range :dtype type})))
                       [id (select-keys range [:lower :upper])]))
                   scalar-ranges))
        ;; Lowered SSA names retain their exact interval here.  The public local environment still
        ;; carries only authoritative dtypes; this private table is a proof cache, not a type or
        ;; function registry, and a missing entry simply declines certification.
        value-ranges (atom validated-scalar-ranges)
        remember-range! (fn [id range]
                          (when range (swap! value-ranges assoc id range))
                          range)
        known-range (fn [value type]
                      (or (get @value-ranges value) (scalar-range/for-dtype type)))
        retained-type (fn [expression]
                        (or (when (and (seq? expression)
                                       (descriptor/cast-op?
                                        (descriptor/semantic-op expression)))
                              (some-> (descriptor/semantic-op expression)
                                      descriptor/cast-result-tag
                                      dtype/dtype-for-scalar-tag))
                            (some-> (or (:raster.type/tag (meta expression))
                                        (:tag (meta expression)))
                                    dtype/dtype-for-scalar-tag)))
        authoritative-source-type
        (fn authoritative-source-type [expression env]
          (or (retained-type expression)
              (cond
                (instance? raster.compiler.ir.kernel_body.Literal expression)
                (canon-type (:type expression))

                (number? expression)
                (some-> expression types/literal-tag dtype/dtype-for-scalar-tag)

                (boolean? expression) :predicate

                (symbol? expression)
                (some-> (or (get env expression) (get scalar-types expression)) canon-type)

                (descriptor/aget-call? expression)
                (some-> (get array-types (descriptor/aget-array-sym expression)) canon-type)

                (and (seq? expression) (descriptor/cast-op? (first expression)))
                (some-> (descriptor/cast-result-tag (first expression))
                        dtype/dtype-for-scalar-tag)

                ;; Canonical Fold owns its scalar result dtype in the typed dialect. This is an
                ;; intrinsic region contract, not an inference from an enclosing consumer cast.
                (dialect/scalar-fold-form? expression)
                (some-> expression dialect/scalar-fold-parts :attributes :dtype canon-type)

                (dialect/scalar-convert-form? expression)
                (some-> expression dialect/scalar-convert-parts
                        :attributes :target-dtype canon-type)

                ;; The canonical ordered-loop matcher supplies the only source loop shape this
                ;; lowerer accepts. Prove its carry from the initializer, then type the update in
                ;; the lexical accumulator/index scope and require an invariant dtype before the
                ;; exit can establish the loop result. No arbitrary loop inference is admitted.
                (and (seq? expression) (contains? #{'loop 'loop*} (first expression)))
                (when-let [{:keys [acc-sym acc-init index-sym update-expr else-expr]}
                           (match-ordered-loop expression)]
                  (when-let [initial-type (authoritative-source-type acc-init env)]
                    (let [loop-env (assoc env index-sym :long acc-sym (canon-type initial-type))
                          update-type (authoritative-source-type update-expr loop-env)]
                      (when (and update-type
                                 (= (canon-type initial-type) (canon-type update-type)))
                        (if (= else-expr acc-sym)
                          (canon-type initial-type)
                          (authoritative-source-type else-expr loop-env))))))

                ;; A lexical result is authoritative when every preceding binder obtains its
                ;; dtype from its own annotation or initializer and the final expression can be
                ;; typed in that extended environment. This is a type-only ordered walk: it must
                ;; not call `lower-let`, evaluate an initializer, or duplicate emitted effects.
                (and (seq? expression)
                     (contains? #{'let 'let* 'clojure.core/let} (first expression)))
                (let [[_ bindings & body-expressions] expression]
                  (when (and (vector? bindings) (even? (count bindings))
                             (= 1 (count body-expressions)))
                    (when-let [extended
                               (reduce
                                (fn [environment [id init]]
                                  (when environment
                                    (when-let [binding-type
                                               (or (retained-type id)
                                                   (authoritative-source-type init environment))]
                                      (assoc environment id (canon-type binding-type)))))
                                env (partition 2 bindings))]
                      (authoritative-source-type (first body-expressions) extended))))

                ;; The shared inference layer owns scalar promotion/result contracts. Invoke it
                ;; only after every operand has an independent type; its legacy partial-operand
                ;; fallback must never turn an unknown expression into evidence for a cast.
                (and (seq? expression)
                     (let [intrinsic (some-> expression descriptor/semantic-op
                                              intrinsics/canonical intrinsics/descriptor)]
                       (and intrinsic (not= :cmp (:kind intrinsic)))))
                (let [arguments (vec (descriptor/call-args expression))
                      argument-types (mapv #(authoritative-source-type % env) arguments)]
                  (when (and (seq arguments) (every? some? argument-types))
                    (let [source-operation (descriptor/semantic-op expression)
                          qualified-operation (when (and (symbol? source-operation)
                                                         (nil? (namespace source-operation)))
                                                (symbol "clojure.core"
                                                        (name source-operation)))
                          inference-operation
                          (if (and qualified-operation
                                   (not (contains? util/*shadowing-locals* source-operation))
                                   (descriptor/scalar-op? qualified-operation))
                            qualified-operation source-operation)
                          inference-parameters
                          (mapv #(symbol (str "%source-operand" %))
                                (range (count argument-types)))
                          type-env
                          (into {}
                                (map (fn [id type]
                                       [id {:tag (:scalar-tag (dtype/info
                                                               (canon-type type)))}])
                                     inference-parameters argument-types))
                          inference-expression (apply list inference-operation
                                                      inference-parameters)]
                      (some-> (inference/infer-expr-tag inference-expression type-env *ns*)
                              dtype/dtype-for-scalar-tag canon-type))))

                ;; A value conditional owns a result type when both alternatives independently
                ;; prove the same type. The enclosing cast target contributes no evidence.
                (and (seq? expression) (= 'if (first expression)) (= 4 (count expression)))
                (let [then-type (authoritative-source-type (nth expression 2) env)
                      else-type (authoritative-source-type (nth expression 3) env)]
                  (when (and then-type else-type
                             (= (canon-type then-type) (canon-type else-type)))
                    (canon-type then-type)))

                (and (seq? expression)
                     (= :cmp (:kind (intrinsics/descriptor
                                     (intrinsics/canonical
                                      (descriptor/semantic-op expression))))))
                :predicate)))
        source-type
        (fn source-type [expression expected env]
          (or
           (retained-type expression)
           (when require-source-types?
             (authoritative-source-type expression env))
           (cond
               (and (seq? expression)
                    (contains? #{'let 'let* 'clojure.core/let} (first expression)))
               (decline! :scalar-source-type
                         "scalar let used at a conversion boundary requires a retained result dtype"
                         {:expression expression :consumer-dtype expected})

               (instance? raster.compiler.ir.kernel_body.Literal expression) (:type expression)
               (symbol? expression) (or (get env expression) (get scalar-types expression) expected)
               (number? expression) expected
               (descriptor/aget-call? expression)
               (or (get array-types (descriptor/aget-array-sym expression)) expected)
               (and (seq? expression) (descriptor/cast-op? (first expression)))
               (dtype/dtype-for-scalar-tag (descriptor/cast-result-tag (first expression)))
               (and (seq? expression)
                    (= :cmp (:kind (intrinsics/descriptor
                                    (intrinsics/canonical
                                     (descriptor/semantic-op expression))))))
               :predicate
               :else (if (and require-source-types? (seq? expression))
                       (decline! :scalar-source-type
                                 "scalar conversion requires the retained source expression dtype"
                                 {:expression expression :consumer-dtype expected
                                  :environment env :scalar-types scalar-types})
                       expected))))]
    (when-not (and (fn? lower-index) (fn? decline!))
      (throw (ex-info "scalar KernelBody lowering requires index and decline callbacks"
                      {:reason :raster/bug :lower-index lower-index :decline decline!})))
    (letfn [(load-ssa [array coordinates]
              (let [type (some-> (get array-types array) dtype/canon)]
                (when-not (and (contains? arrays array) type)
                  (decline! :indexed-load "scalar loads require a declared typed stable tensor"
                            {:array array :array-types array-types}))
                (reserve! [array coordinates predicate])
                (let [id (fresh "load") range (scalar-range/for-dtype type)]
                  (remember-range! id range)
                  {:operations [(body/->ScalarLoad
                                 (body/value id type) array coordinates predicate
                                 (when predicate (if load-other (load-other type)
                                                     (body/literal 0 type))) :cached)]
                   :result id :type type :range range})))

            (compute-ssa [operator result-type arguments options range]
              (reserve! arguments)
              (let [result-type (canon-type result-type)
                    result (fresh "value")
                    range (or range (scalar-range/for-dtype result-type))]
                (remember-range! result range)
                {:operations [(body/->ScalarCompute
                               (body/value result result-type)
                               (body/scalar-expression operator result-type arguments options))]
                 :result result :type result-type :range range}))

            (cast-lowered [lowered target expression & [explicit-narrowing]]
              (let [target (dtype/canon target)]
                (if (= target (:type lowered))
                  lowered
                  (let [source (dtype/canon (:type lowered))
                        [rounding overflow]
                        ;; An explicit source cast owns its checked-versus-unchecked narrowing
                        ;; contract. Implicit conversions continue to use the owner's policy, or
                        ;; the legacy map/fold wrap default when the owner supplies none.
                        (or (case explicit-narrowing
                              :wrap (scalar-conversion/policy source target :wrap)
                              :reject (scalar-conversion/policy source target :trap)
                              nil (if conversion-policy
                                    (conversion-policy source target)
                                    (scalar-conversion/policy source target :wrap)))
                            (decline! :cast-policy
                                      "scalar cast has no portable rounding and overflow policy"
                                      {:expression expression :source source :target target}))
                        ;; A checked integral narrowing remains a conversion, so its operand is
                        ;; still evaluated exactly once.  When the producer's retained interval
                        ;; proves every possible value representable by the target, however, the
                        ;; checked conversion is total and needs no target trap instruction.
                        [rounding overflow]
                        (if (and (= :reject explicit-narrowing)
                                 (not (dtype/fp-dtype? source))
                                 (not (dtype/fp-dtype? target))
                                 (scalar-range/contained-in-dtype? (:range lowered) target))
                          [:exact :exact]
                          [rounding overflow])
                        id (fresh "cast")]
                    (let [range (when (scalar-range/contained-in-dtype? (:range lowered) target)
                                  (:range lowered))]
                      (remember-range! id (or range (scalar-range/for-dtype target)))
                      {:operations (conj (:operations lowered)
                                       (body/->ScalarCompute
                                        (body/value id target)
                                        (body/cast-expression (:result lowered) target
                                                              rounding overflow)))
                       :result id :type target :range (or range (scalar-range/for-dtype target))})))))

            (lower-ordered-bindings
              [bindings env resolve-binding-type mismatch-rule mismatch-message]
              (reduce
               (fn [{:keys [operations substitutions environment]} [id init]]
                 (let [init (util/subst-syms substitutions init)
                       binding-type (canon-type (resolve-binding-type id init environment))
                       lowered (lower init binding-type environment)
                       _ (when-not (= binding-type (:type lowered))
                           (decline! mismatch-rule mismatch-message
                                     {:binding id :initializer init
                                      :expected binding-type :actual (:type lowered)}))
                       result (:result lowered)
                       ;; Substituted SSA references retain their definition dtype for subsequent
                       ;; source expressions and storage-coordinate lowering.
                       tag (when-not (= :predicate binding-type)
                             (:scalar-tag (dtype/info binding-type)))
                       result (if (and (symbol? result) tag)
                                (with-meta result
                                  (assoc (meta result) :raster.type/tag tag))
                                result)]
                   {:operations (into operations (:operations lowered))
                    :substitutions (assoc substitutions id result)
                    :environment (cond-> environment
                                   (symbol? result) (assoc result binding-type))}))
               {:operations [] :substitutions {} :environment env}
               (partition 2 bindings)))

            (lower-let [expression expected env]
              (let [[_ bindings & body-expressions] expression
                    ids (when (vector? bindings) (take-nth 2 bindings))]
                (when-not (and (vector? bindings) (even? (count bindings))
                               (every? symbol? ids) (= (count ids) (count (set ids)))
                               (= 1 (count body-expressions)))
                  (decline! :scalar-let-shape
                            "scalar let requires distinct ordered bindings and one result"
                            {:expression expression :bindings bindings
                             :body-count (count body-expressions)}))
                (let [{:keys [operations substitutions environment]}
                      (lower-ordered-bindings
                       bindings env
                       (fn [id init environment]
                         (or (retained-type id)
                             (authoritative-source-type init environment)
                             (decline! :scalar-let-binding-dtype
                                       "scalar let binding lacks an authoritative source dtype"
                                       {:binding id :initializer init
                                        :environment (set (keys environment))})))
                       :scalar-let-binding-dtype
                       "scalar let initializer disagrees with its retained dtype")
                      result-expression (util/subst-syms substitutions (first body-expressions))
                      result (lower result-expression expected environment)
                      result (if (= expected (:type result))
                               result
                               (cast-lowered result expected expression))]
                  (update result :operations #(into operations %)))))

            (lower [expression expected env]
              (let [lexical-let? (and (seq? expression)
                                      (contains? #{'let 'let* 'clojure.core/let} (first expression)))
                    ;; Strict typed owners preserve operation width before any consumer cast.
                    ;; Older packed owners retain their explicit widened-integer policy.
                    expected (canon-type expected)
                    _ (when (and require-source-types? (seq? expression) (not lexical-let?))
                        (source-type expression expected env))
                    retained (when (seq? expression) (retained-type expression))
                    operation-type (if (and retained
                                            (or require-source-types?
                                                (and (dtype/fp-dtype? expected)
                                                     (dtype/fp-dtype? retained))))
                                     retained expected)
                    lowered (if lexical-let?
                              (lower-let expression operation-type env)
                              (lower-value expression operation-type env))]
                ;; Loads and explicit source conversions retain their own result dtype. The
                ;; consumer boundary must convert that actual result, not the requested hint.
                (if (not= (:type lowered) expected)
                  (cast-lowered lowered expected expression)
                  lowered)))

            (lower-value [expression expected env]
                (cond
                  (instance? raster.compiler.ir.kernel_body.Literal expression)
                  {:operations [] :result expression
                   :type (canon-type (:type expression))
                   :range (scalar-range/literal (:value expression) (:type expression))}

                  (and (= :predicate expected) (number? expression))
                  (if (contains? #{0 1} expression)
                    {:operations [] :result (body/literal (= 1 expression) :predicate)
                     :type :predicate}
                    (decline! :predicate-literal
                              "numeric predicates must use the canonical zero/one encoding"
                              {:expression expression}))

                  (number? expression)
                  (let [range (scalar-range/literal expression expected)]
                    {:operations [] :result (body/literal expression expected)
                     :type expected :range range})

                  (boolean? expression)
                  {:operations [] :result (body/literal expression :predicate) :type :predicate}

                  (symbol? expression)
                  (if-let [actual (or (get env expression) (get scalar-types expression))]
                    (let [type (canon-type actual)]
                      {:operations [] :result expression :type type
                       :range (known-range expression type)})
                    (if-let [constant (numeric-constant/value expression)]
                      (lower-value (:value constant) expected env)
                      (decline! :unbound-scalar
                                "scalar expression references an undeclared value"
                                {:expression expression :environment (set (keys env))})))

                  (descriptor/aget-call? expression)
                  (let [array (descriptor/aget-array-sym expression)
                        arguments (vec (descriptor/call-args expression))
                        coordinate (last arguments)
                        array-type (some-> (get array-types array) dtype/canon)]
                    (when-not (and (= 2 (count arguments)) (contains? arrays array) array-type)
                      (decline! :indexed-load
                                "scalar loads require a declared typed stable tensor"
                                {:expression expression :array array :array-types array-types}))
                    (let [coordinate-value
                          (when (contains-indexed-load? coordinate)
                            ;; Storage coordinates are address arithmetic. Keep their composed
                            ;; SSA in the KernelBody index width; narrowing a long launch index to
                            ;; an element dtype would either overflow or invent a cast policy.
                            (lower coordinate :long env))
                          coordinate-expression
                          (if coordinate-value
                            (:result coordinate-value)
                            (lower-index coordinate (set (keys env))))
                          loaded (load-ssa array [coordinate-expression])]
                      (update loaded :operations #(into (vec (:operations coordinate-value)) %))))

                  (and (seq? expression) (descriptor/cast-op? (first expression))
                       (= 2 (count expression)))
                  (let [target (dtype/dtype-for-scalar-tag
                                (descriptor/cast-result-tag (first expression)))
                        source-expected (dtype/canon
                                         (or (authoritative-source-type (second expression) env)
                                             (decline! :scalar-source-type
                                                       "explicit scalar cast requires the retained operand dtype"
                                                       {:expression expression
                                                        :operand (second expression)
                                                        :target target})))
                        lowered (lower (second expression) source-expected env)]
                    (cast-lowered lowered target expression
                                  (descriptor/cast-integral-narrowing (first expression))))

                  (dialect/scalar-convert-form? expression)
                  (let [{:keys [attributes operand]} (dialect/scalar-convert-parts expression)
                        {:keys [source-dtype target-dtype rounding overflow]} attributes
                        _ (when-not (and (dialect/scalar-convert-attributes? attributes)
                                         (= (canon-type target-dtype) expected))
                            (decline! :typed-scalar-convert
                                      "typed scalar conversion must match its consumer dtype"
                                      {:expression expression :expected expected
                                       :attributes attributes}))
                        lowered (lower operand (canon-type source-dtype) env)
                        _ (when-not (= (canon-type source-dtype) (:type lowered))
                            (decline! :typed-scalar-convert-source
                                      "typed scalar conversion operand disagrees with its source dtype"
                                      {:expression expression :expected source-dtype
                                       :actual (:type lowered)}))]
                    (if (= (canon-type source-dtype) (canon-type target-dtype))
                      lowered
                      (let [range (when (scalar-range/contained-in-dtype?
                                         (:range lowered) target-dtype)
                                    (:range lowered))
                            overflow (if (and (= :trap overflow) range) :exact overflow)
                            id (fresh "convert")]
                        (remember-range! id (or range (scalar-range/for-dtype target-dtype)))
                        {:operations
                         (conj (:operations lowered)
                               (body/->ScalarCompute
                                (body/value id target-dtype)
                                (body/cast-expression (:result lowered) target-dtype
                                                      rounding overflow)))
                         :result id :type target-dtype
                         :range (or range (scalar-range/for-dtype target-dtype))})))

                  (and (seq? expression)
                       (= 'raster.numeric/oftype (descriptor/semantic-op expression))
                       (= 2 (count (descriptor/call-args expression))))
                  (let [value-expression (second (descriptor/call-args expression))
                        source-expected (canon-type (source-type value-expression expected env))
                        lowered (lower value-expression source-expected env)]
                    (cast-lowered lowered expected expression))

                  (and (seq? expression) (= 'if (first expression)) (= 4 (count expression)))
                  (let [[_ condition then-expression else-expression] expression
                        condition (lower condition :predicate env)
                        then-value (lower then-expression expected env)
                        else-value (lower else-expression expected env)
                        result-type (:type then-value)
                        _ (when-not (= result-type (:type else-value) expected)
                            (decline! :branch-dtype
                                      "scalar branches must have one explicit result dtype"
                                      {:expression expression :then (:type then-value)
                                       :else (:type else-value) :expected expected}))
                        result (fresh "if")
                        range (scalar-range/hull [(:range then-value) (:range else-value)])]
                    (remember-range! result range)
                    {:operations
                     (conj (vec (:operations condition))
                           (body/->IfRegion
                            (:result condition)
                            (conj (vec (:operations then-value))
                                  (body/->Yield [(:result then-value)]))
                            (conj (vec (:operations else-value))
                                  (body/->Yield [(:result else-value)]))
                            [(body/value result result-type)]))
                     :result result :type result-type :range range})

                  (dialect/scalar-fold-form? expression)
                  (let [{:keys [attributes lambda]} (dialect/scalar-fold-parts expression)
                        {parameters :parameters fold-locals :locals
                         body-results :body-results} (dialect/lambda-parts lambda)
                        [accumulator index] parameters
                        fold-type (canon-type (:dtype attributes))
                        _ (when-not (and (= 2 (count parameters))
                                         (= 1 (count body-results)) (= fold-type expected))
                            (decline! :typed-scalar-fold-shape
                                      "canonical scalar fold must match its expected typed result"
                                      {:expression expression :expected expected
                                       :dtype fold-type :parameters parameters
                                       :locals fold-locals :results body-results}))
                        loop-index (fresh "fold-index")
                        carry (fresh "fold-carry")
                        result (fresh "fold-result")
                        initial (lower (:identity attributes) fold-type env)
                        local-state
                        (reduce
                         (fn [{:keys [operations substitutions environment]} local]
                           (let [local-type (canon-type (:dtype local))
                                 local-expression (util/subst-syms substitutions (:init local))
                                 lowered (lower local-expression local-type environment)
                                 local-result (:result lowered)
                                 tag (:scalar-tag (dtype/info local-type))
                                 local-result (if (and (symbol? local-result) tag)
                                                (with-meta local-result
                                                  (assoc (meta local-result)
                                                         :raster.type/tag tag))
                                                local-result)]
                             (when-not (= local-type (:type lowered))
                               (decline! :typed-scalar-fold-local-dtype
                                         "canonical Fold local must preserve its retained dtype"
                                         {:expression expression :local local
                                          :actual (:type lowered)}))
                             {:operations (into operations (:operations lowered))
                              :substitutions (assoc substitutions (:id local) local-result)
                              :environment (cond-> environment
                                             (symbol? local-result)
                                             (assoc local-result local-type))}))
                         {:operations []
                          :substitutions {index loop-index accumulator carry}
                          :environment (assoc env loop-index :long carry fold-type)}
                         fold-locals)
                        update-expression (util/subst-syms (:substitutions local-state)
                                                           (first body-results))
                        update (lower update-expression fold-type (:environment local-state))
                        _ (when-not (= fold-type (:type initial) (:type update))
                            (decline! :typed-scalar-fold-dtype
                                      "canonical scalar fold carry dtype must remain invariant"
                                      {:expression expression :initial (:type initial)
                                       :update (:type update) :dtype fold-type}))
                        loop-operation
                        (body/->ForLoop
                         (body/value loop-index :long)
                         (lower-index (:lower attributes 0) (set (keys env)))
                         (lower-index (:extent attributes) (set (keys env)))
                         1
                         [(body/->LoopArg (body/value carry fold-type) (:result initial))]
                         (conj (into (vec (:operations local-state)) (:operations update))
                               (body/->Yield [(:result update)]))
                         [(body/value result fold-type)]
                         (cond-> {:association (:association attributes)
                                  :source-order (= :ordered (:association attributes))}
                           (= :inclusive (:upper-bound attributes))
                           (assoc :upper-bound :inclusive)
                           (:algebra attributes) (assoc :algebra (:algebra attributes))))]
                    {:operations (conj (vec (:operations initial)) loop-operation)
                     :result result :type fold-type})

                  (and (seq? expression) (contains? #{'loop 'loop*} (first expression)))
                  (if-let [{:keys [acc-sym acc-init index-sym bound-expr else-expr update-expr
                                   inclusive? index-init]}
                           (match-ordered-loop expression)]
                    (do
                      (when (or (patterns/contains-sym? bound-expr index-sym)
                                (patterns/contains-sym? bound-expr acc-sym)
                                (patterns/contains-sym? else-expr index-sym))
                        (decline! :ordered-loop-shape
                                  "ordered scalar loop requires an invariant upper bound and an exit over its carry"
                                  {:expression expression :bound bound-expr
                                   :index index-sym :accumulator acc-sym :exit else-expr}))
                      (let [loop-index (fresh "loop-index")
                            carry (fresh "loop-carry")
                            result (fresh "loop-result")
                            ;; `(loop [i 0 s init] (if (< i n) (recur (inc i) step) exit))` is the
                            ;; ordered fold followed by `exit` over the final carry. The carry keeps
                            ;; the step's own dtype so the exit's cast (e.g. `(double s)`) is an
                            ;; explicit conversion rather than a silent widening of the fold.
                            exit? (not= else-expr acc-sym)
                            initial-source-type (authoritative-source-type acc-init env)
                            carry-source-env (cond-> (assoc env index-sym :long)
                                               initial-source-type
                                               (assoc acc-sym (canon-type initial-source-type)))
                            carry-type (if exit?
                                         (canon-type
                                          (or (authoritative-source-type
                                               update-expr carry-source-env)
                                              (source-type update-expr expected
                                                           carry-source-env)))
                                         expected)
                            initial (lower acc-init carry-type env)
                            loop-type (:type initial)
                            update (util/subst-syms {index-sym loop-index acc-sym carry}
                                                    update-expr)
                            lowered (lower update loop-type
                                           (assoc env loop-index :long carry loop-type))
                            _ (when-not (= loop-type (:type lowered))
                                (decline! :ordered-loop-dtype
                                          "ordered scalar loop carry dtype must remain invariant"
                                          {:expression expression :initial loop-type
                                           :update (:type lowered)}))
                            upper (lower-index bound-expr (set (keys env)))
                            loop (body/->ForLoop
                                  (body/value loop-index :long)
                                  (body/index-cast index-init :long :exact)
                                  upper 1
                                  [(body/->LoopArg (body/value carry loop-type)
                                                   (:result initial))]
                                  (conj (vec (:operations lowered))
                                        (body/->Yield [(:result lowered)]))
                                  [(body/value result loop-type)]
                                  (cond-> {:association :ordered}
                                    inclusive? (assoc :upper-bound :inclusive)))
                            exit (when exit?
                                   (lower (util/subst-syms {acc-sym result} else-expr)
                                          expected (assoc env result loop-type)))]
                        (if exit
                          {:operations (into (conj (vec (:operations initial)) loop)
                                             (:operations exit))
                           :result (:result exit) :type (:type exit)}
                          {:operations (conj (vec (:operations initial)) loop)
                           :result result :type loop-type})))
                    (decline! :ordered-loop-shape
                              "scalar loop is outside the canonical ordered carry form"
                              {:expression expression}))

                  ;; `inc`/`dec` are the closed-core index steppers: `(+ x 1)` / `(- x 1)` with the
                  ;; same operand dtype and overflow policy. Normalize before intrinsic lookup so
                  ;; the KernelBody vocabulary stays binary.
                  (and (seq? expression) (= 2 (count expression))
                       (contains? '#{inc clojure.core/inc} (first expression)))
                  (lower (normalized-form (list 'clojure.core/+ (second expression) 1)
                                          expected expression) expected env)

                  (and (seq? expression) (= 2 (count expression))
                       (contains? '#{dec clojure.core/dec} (first expression)))
                  (lower (normalized-form (list 'clojure.core/- (second expression) 1)
                                          expected expression) expected env)

                  ;; Unary subtraction is the existing negation intrinsic for floating values:
                  ;; spelling it as 0-x would lose the sign of zero. Integral negation instead
                  ;; uses the checked/wrapping subtraction machinery, including MIN_VALUE.
                  (and (seq? expression)
                       (= :- (intrinsics/canonical (descriptor/semantic-op expression)))
                       (= 1 (count (descriptor/call-args expression))))
                  (lower (normalized-form (if (dtype/fp-dtype? expected)
                           (list :neg (first (descriptor/call-args expression)))
                           (list (descriptor/semantic-op expression)
                                 (body/literal 0 expected)
                                 (first (descriptor/call-args expression)))) expected expression)
                         expected env)

                  (and (seq? expression)
                       (= :java-round (:typed-expansion
                                       (intrinsics/descriptor
                                        (intrinsics/canonical (descriptor/semantic-op expression))))))
                  (let [arguments (vec (descriptor/call-args expression))
                        intrinsic (intrinsics/descriptor
                                   (intrinsics/canonical (descriptor/semantic-op expression)))
                        _ (when-not (= 1 (count arguments))
                            (decline! :scalar-expression "Java round requires one argument"
                                      {:expression expression}))
                        input-type (source-type (first arguments) nil env)
                        result-type (get (:source-signatures intrinsic) input-type)
                        _ (when-not result-type
                            (decline! :scalar-source-type "Java round requires a retained floating overload"
                                      {:expression expression :source input-type}))
                        input (lower (first arguments) input-type env)
                        base (compute-ssa :floor input-type [(:result input)] {} nil)
                        fraction (compute-ssa :- input-type [(:result input) (:result base)] {} nil)
                        up (compute-ssa :ge :predicate [(:result fraction) (body/literal 0.5 input-type)] {} nil)
                        next (compute-ssa :+ input-type [(:result base) (body/literal 1.0 input-type)] {} nil)
                        rounded (compute-ssa :select input-type [(:result up) (:result next) (:result base)] {} nil)
                        converted (compute-ssa :cast result-type [(:result rounded)]
                                               {:rounding :toward-zero :overflow :saturate} nil)]
                    ;; Adding 0.5 before floor would double-round the predecessor of 0.5.
                    ;; Saturation supplies Java's NaN=0 and signed endpoint semantics.
                    (cast-lowered (assoc converted :operations
                                         (vec (mapcat :operations
                                                      [input base fraction up next rounded converted])))
                                  expected expression))

                  (seq? expression)
                  (let [semantic-operation (descriptor/semantic-op expression)
                        operator (intrinsics/canonical semantic-operation)
                        intrinsic (intrinsics/descriptor operator)
                        arguments (vec (descriptor/call-args expression))]
                    (when-not intrinsic
                      (decline! :scalar-expression
                                "scalar expression has no canonical intrinsic"
                                {:expression expression :operator operator}))
                    (if (and (= 2 (:arity intrinsic)) (> (count arguments) 2)
                             (contains? #{:+ :* :- :div :min :max} operator))
                      ;; Preserve source evaluation order while spelling variadic scalar folds in
                      ;; the binary KernelBody vocabulary. This is normalization, not algebraic
                      ;; reassociation: `(- a b c)` becomes `(- (- a b) c)`.
                      (lower (reduce (fn [left right]
                                       (normalized-form (list (descriptor/semantic-op expression) left right)
                                                        expected expression))
                                     arguments)
                             expected env)
                      (do
                        (when-not (= (:arity intrinsic) (count arguments))
                          (decline! :scalar-expression
                                    "scalar expression has the wrong intrinsic arity"
                                    {:expression expression :operator operator
                                     :expected (:arity intrinsic)
                                     :actual (count arguments)}))
                        (let [comparison? (= :cmp (:kind intrinsic))
                              ;; An enclosing consumer dtype is not the source arithmetic dtype.
                              ;; When operand facts determine a checked Long addition feeding a
                              ;; Float stage, compute the addition as Long and convert its result;
                              ;; converting operands first changes both overflow and rounding.
                              source-result-type
                              (when-not comparison?
                                (dtype/canon (source-type expression expected env)))
                              operand-type (if comparison?
                                             (dtype/canon
                                              (or (source-type (first arguments) :int env) :int))
                                             source-result-type)
                              lowered (mapv #(cast-lowered
                                              (lower % operand-type env)
                                              operand-type expression)
                                            arguments)
                              result-type (if comparison? :predicate source-result-type)
                              ;; Typed source arithmetic has a semantic overflow contract: normal
                              ;; Clojure integral arithmetic is checked, while the explicitly
                              ;; `unchecked-*` forms wrap.  Retain that distinction in KernelBody
                              ;; rather than leaving a C-family emitter to choose signed overflow.
                              integral-arithmetic?
                              (and (contains? #{:byte :int :long} operand-type)
                                   (contains? #{:+ :- :*} operator))
                              operand-ranges (mapv :range lowered)
                              proven-range (when integral-arithmetic?
                                             (scalar-range/arithmetic operator operand-ranges))
                              overflow (when integral-arithmetic?
                                         (or (intrinsics/source-overflow-policy semantic-operation)
                                             (when (scalar-range/contained-in-dtype? proven-range operand-type)
                                               :no-overflow)
                                             :trap))
                              options (cond-> {} overflow (assoc :overflow overflow)
                                               (= :no-overflow overflow)
                                               (assoc :proof (assoc proven-range
                                                              :kind :typed-scalar-range)))
                              _ (when-not (every? #(= operand-type (:type %)) lowered)
                                  (decline! :operand-dtype
                                            "scalar intrinsic operands require one dtype"
                                            {:expression expression :operand-type operand-type
                                             :actual (mapv :type lowered)}))
                              result-range (if (= :quot operator)
                                             (scalar-range/quotient operand-ranges)
                                             proven-range)
                              computed (compute-ssa operator result-type (mapv :result lowered)
                                                    options (when (scalar-range/contained-in-dtype?
                                                                    result-range result-type)
                                                              result-range))
                              computed (update computed :operations
                                               #(into (vec (mapcat :operations lowered)) %))]
                          (if (or comparison? (nil? expected)
                                  (= result-type (dtype/canon expected)))
                            computed
                            (cast-lowered computed expected expression))))))

                  :else
                  (decline! :scalar-expression
                            "scalar expression has an unsupported value"
                            {:expression expression :type (type expression)})))]
      ;; Reserve at public region boundaries, not at every recursive child: identifiers are
      ;; scoped facts, and rescanning each subtree would make deeply nested lowering quadratic.
      {:fresh-binding fresh
       :lower (fn [expression expected env]
                ;; A proved coordinate may introduce owner SSA names after source projection.
                (reserve! [expression (when-not (some? source-region) (keys env)) predicate])
                (lower expression expected env))
       :cast (fn [lowered target expression]
               (reserve! [lowered expression predicate])
               (cast-lowered lowered target expression))
       ;; These typed entries perform no source admission, index proof, promotion or overflow
       ;; inference. Their owner supplies proved coordinates and already-converted operands.
       :load load-ssa
       :compute (fn [operator result-type arguments options]
                  (compute-ssa operator result-type arguments options nil))
       :lower-region
       (fn [{:keys [bindings results]} result-types binding-types env]
         ;; Later binders matter too: substitutions must never capture a generated earlier ID.
         (reserve! [bindings results (keys env) predicate])
         ;; Region locals are evaluated once, in source order. In particular, a product's
         ;; shared combine bindings must not be beta-expanded separately into every result.
         ;; Types are retained facts supplied by the caller, never guessed from a consumer.
         (when-not (and (vector? bindings) (even? (count bindings))
                        (every? symbol? (take-nth 2 bindings))
                        (= (count (take-nth 2 bindings))
                           (count (set (take-nth 2 bindings))))
                        (vector? results) (= (count results) (count result-types)))
           (decline! :scalar-region-shape
                     "scalar region requires distinct ordered bindings and typed results"
                     {:bindings bindings :results results :result-types result-types}))
         (let [checked-lower
               (fn [expression expected local-env]
                 (let [expected (canon-type expected)
                       lowered (lower expression expected local-env)]
                   (when-not (= expected (:type lowered))
                     (decline! :scalar-region-dtype
                               "scalar region value disagrees with its retained dtype"
                               {:expression expression :expected expected
                                :actual (:type lowered)}))
                   lowered))
               {:keys [operations substitutions environment]}
               (lower-ordered-bindings
                bindings env
                (fn [id expression _]
                  (or (get binding-types id)
                      (decline! :scalar-region-binding-dtype
                                "scalar region binding lacks a retained dtype"
                                {:binding id :expression expression})))
                :scalar-region-dtype
                "scalar region value disagrees with its retained dtype")
               lowered-results
               (mapv (fn [expression expected]
                       (checked-lower (util/subst-syms substitutions expression)
                                      expected environment))
                     results result-types)]
           {:operations (into operations (mapcat :operations lowered-results))
            :results (mapv :result lowered-results)
            :types (mapv :type lowered-results)}))})))
