(ns raster.wasm
  "Runtime half of the raster cljs↔wasm binding (browser).

   Every namespace generated by `raster.compiler.cljs-emit` sits on top of this:
   it instantiates a raster-compiled wasm module, resolves exports, and hands
   back typed-array views over the module's single shared linear memory. This is
   not asteroids-specific — it is the runtime any raster→wasm kernel ns requires.

   The (ptr,len) ABI: array kernel args are byte-offsets into `memory`; the app
   reads/writes element data through the typed-array views (zero-copy). `env` is
   the import object for ops with no native wasm opcode (transcendentals →
   js/Math); empty for kernels that only use native ops."
  (:require [applied-science.js-interop :as j]))

(defn instantiate!
  "Instantiate a raster wasm module. `src` is a URL string (fetched) or the wasm
   bytes (js/ArrayBuffer or typed array). `env` is the import object (default {}).
   Returns a promise of {:instance :exports :memory}."
  ([src] (instantiate! src #js {}))
  ([src env]
   (let [imports #js {:env env}
         finish  (fn [result]
                   (let [inst (j/get result :instance)
                         exp  (j/get inst :exports)]
                     {:instance inst :exports exp :memory (j/get exp :memory)}))]
     (if (string? src)
       (-> (js/fetch src)
           (.then (fn [r] (.arrayBuffer r)))
           (.then (fn [buf] (js/WebAssembly.instantiate buf imports)))
           (.then finish))
       (-> (js/WebAssembly.instantiate src imports)
           (.then finish))))))

(defn export   [m n] (j/get (:exports m) n))
(defn memory   [m] (:memory m))
(defn buffer   [m] (j/get (:memory m) :buffer))
(defn f64-view [m] (js/Float64Array. (buffer m)))
(defn f32-view [m] (js/Float32Array. (buffer m)))
(defn i32-view [m] (js/Int32Array. (buffer m)))
