;; GENERATED by raster.compiler.cljs-emit — do not edit.
;; cljs counterpart of the raster kernel ns voxel.kernels (deftm/defvalue → wasm).
(ns voxel.kernels
  (:require [raster.wasm :as w]))

(defonce M (atom nil))
(defn init!
  ([src] (init! src (cljs.core/js-obj)))
  ([src env] (.then (w/instantiate! src env) (fn [s] (reset! M s) s))))
(defn ready? [] (some? @M))
(defn- kfn [n] (w/export @M n))

(defn terrain-height [x z] ((kfn "terrain_height") x z))
