(ns raster.ci.timing-weights
  "Explicit, reviewable import of CI timing artifacts. Never updates weights during a test run."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(defn report-costs [report]
  (when-not (= 1 (:schema-version report))
    (throw (ex-info "unsupported CI timing schema" {})))
  (when-not (map? (:namespaces report))
    (throw (ex-info "CI timing report requires a namespace map" {})))
  (into {}
        (for [[n times] (:namespaces report)]
          (let [durations (map #(get times % 0) [:load-ns :test-ns])]
            (when-not (and (symbol? n) (map? times)
                           (some #(contains? times %) [:load-ns :test-ns])
                           (every? #(and (integer? %) (<= 0 % Long/MAX_VALUE)) durations))
              (throw (ex-info "invalid namespace timing" {:namespace n :timings times})))
            [n (max 1 (long (Math/ceil (/ (double (reduce +' durations)) 1e6))))]))))

(defn test-paths []
  (into {}
        (for [file (file-seq (io/file "test"))
              :when (and (.isFile file) (str/ends-with? (.getName file) "_test.clj"))]
          (with-open [reader (java.io.PushbackReader. (io/reader file))]
            (let [form (binding [*read-eval* false] (read reader))]
              (when-not (and (seq? form) (= 'ns (first form)) (symbol? (second form)))
                (throw (ex-info "test file must start with a namespace declaration"
                                {:file (str file)})))
              [(second form) (.getPath file)])))))

(defn -main [output source & reports]
  (when-not (and output source (seq reports))
    (throw (ex-info "usage: timing-weights OUTPUT SOURCE REPORT..." {})))
  (let [paths (test-paths)
        ;; Repeated measurements use their maximum as a conservative bootstrap. Review and
        ;; refresh from comparable CI runs; load attribution changes when partitioning changes.
        costs (apply merge-with max (map #(report-costs (edn/read-string (slurp %))) reports))
        rows (sort-by first (keep (fn [[n cost]] (when-let [path (get paths n)] [path cost]))
                                 costs))]
    (when-not (seq rows)
      (throw (ex-info "timing reports contain no current test namespaces" {})))
    (io/make-parents output)
    (spit output (str "# CI load + test milliseconds; source: " source "\n"
                      "# Generated by raster.ci.timing-weights; new files use calibrated byte estimates.\n"
                      (str/join "\n" (map #(str/join "\t" %) rows)) "\n"))
    (println "Wrote" (count rows) "reviewable timing weights to" output)))
