;; GENERATED by raster.compiler.cljs-emit — do not edit.
;; cljs counterpart of the raster kernel ns asteroids.kernels (deftm/defvalue → wasm).
(ns asteroids.kernels
  (:require [raster.wasm :as w]))

(defonce M (atom nil))
(defn init!
  ([src] (init! src (cljs.core/js-obj)))
  ([src env] (.then (w/instantiate! src env) (fn [s] (reset! M s) s))))
(defn ready? [] (some? @M))
(defn- kfn [n] (w/export @M n))

(defrecord Shape [x y vx vy angle spin size])
(defn move-shape [s dt w h] (let [r ((kfn "move_shape") (:x s) (:y s) (:vx s) (:vy s) (:angle s) (:spin s) (:size s) dt w h)] (->Shape (aget r 0) (aget r 1) (aget r 2) (aget r 3) (aget r 4) (aget r 5) (aget r 6))))
