;; Compile valley's terrain kernels to wasm + generate the cljs shim (valley.kernels).
;; Run from the repo root:
;;   clojure -Sdeps '{:paths ["src" "examples"]}' -M examples/valley/gen.clj
;; Outputs into the shared asteroids/web playground build:
;;   examples/asteroids/web/public/valley_kernels.wasm
;;   examples/asteroids/web/src/valley/kernels.cljs   (same ns as kernels.clj)
;;
;; Unlike voxel (scalar terrain-height), valley's kernels take permutation-array
;; params, so the generated shim writes the 3 perm tables into wasm linear memory
;; at fixed offsets on init and calls the exports with those pointers — matching
;; the JVM kernels.clj facade exactly (same seeds + biome params → identical terrain).
(require '[raster.compiler.pipeline :as pl]
         '[raster.noise :as noise]
         '[clojure.java.io :as io]
         '[clojure.string :as str])
(require 'valley.core)

(def web-dir "examples/asteroids/web")

;; must match examples/valley/kernels.clj
(def HS 18.0) (def BO -4.0)
(def HP (noise/make-perm 1337))
(def DP (noise/make-perm 9001))
(def CP (noise/make-perm 4242))
;; byte offsets in wasm memory (512 ints * 4 bytes = 2048 each)
(def HP-OFF 0) (def DP-OFF 2048) (def CP-OFF 4096)

(defn js-ints [^ints a] (str "#js [" (str/join " " (map int (seq a))) "]"))

(let [module (pl/compile-wasm-module
              [{:var #'valley.core/terrain-height :name "terrain_height"}
               {:var #'valley.core/has-cave?      :name "has_cave"}])
      wasm   (io/file web-dir "public" "valley_kernels.wasm")
      cljs   (io/file web-dir "src" "valley" "kernels.cljs")
      shim   (str ";; GENERATED by examples/valley/gen.clj — do not edit.\n"
                  ";; cljs counterpart of valley.kernels: wasm terrain kernels with the perm\n"
                  ";; tables written into linear memory at init (the JVM facade is kernels.clj).\n"
                  "(ns valley.kernels (:require [raster.wasm :as w]))\n\n"
                  "(defonce M (atom nil))\n"
                  "(def ^:private HS " HS ") (def ^:private BO " BO ")\n"
                  "(def ^:private HP " (js-ints HP) ")\n"
                  "(def ^:private DP " (js-ints DP) ")\n"
                  "(def ^:private CP " (js-ints CP) ")\n\n"
                  "(defn init! [src]\n"
                  "  (.then (w/instantiate! src)\n"
                  "    (fn [m]\n"
                  "      (let [v (w/i32-view m)]\n"
                  "        (.set v HP " (quot HP-OFF 4) ") (.set v DP " (quot DP-OFF 4) ") (.set v CP " (quot CP-OFF 4) "))\n"
                  "      (reset! M m) m)))\n\n"
                  "(defn terrain-height [x z] ((w/export @M \"terrain_height\") " HP-OFF " " DP-OFF " x z HS BO))\n"
                  "(defn has-cave? [x y z] ((w/export @M \"has_cave\") " CP-OFF " x y z))\n")]
  (io/make-parents wasm)
  (io/make-parents cljs)
  (with-open [o (java.io.FileOutputStream. wasm)] (.write o ^bytes (:bytes module)))
  (spit cljs shim)
  (println "wrote" (.getPath wasm) (count (:bytes module)) "bytes")
  (println "wrote" (.getPath cljs)))

(shutdown-agents)
